const state = {
  currentUser:      null,
  currentToken:     null,
  isAdmin:          false,
  canEdit:          false,
  userRole:         null,
  userOp:           null,
  userBase:         null,
  currentOp:        null,
  currentBase:      null,
  csvData:          [],
  xlsxData:         [],
  logsData:         [],
  slaDsHistory:      [],
  slaDsBases:        [],
  slaDsActiveBases:  [],
  slaDsActiveBases2: [],
  slaDsPeriod:       null,
  slaDsCompare:      false,
  cepCache:         JSON.parse(localStorage.getItem('cep_cache') || '{}'),
  sortStates:       {},
  libSel:           null,
};

Object.defineProperties(window, {
  currentUser:      { get(){ return state.currentUser;      }, set(v){ state.currentUser=v;      } },
  currentToken:     { get(){ return state.currentToken;     }, set(v){ state.currentToken=v;     } },
  isAdmin:          { get(){ return state.isAdmin;          }, set(v){ state.isAdmin=v;          } },
  canEdit:          { get(){ return state.canEdit;          }, set(v){ state.canEdit=v;          } },
  userRole:         { get(){ return state.userRole;         }, set(v){ state.userRole=v;         } },
  userOp:           { get(){ return state.userOp;           }, set(v){ state.userOp=v;           } },
  userBase:         { get(){ return state.userBase;         }, set(v){ state.userBase=v;         } },
  currentOp:        { get(){ return state.currentOp;        }, set(v){ state.currentOp=v;        } },
  currentBase:      { get(){ return state.currentBase;      }, set(v){ state.currentBase=v;      } },
  csvData:          { get(){ return state.csvData;          }, set(v){ state.csvData=v;          } },
  xlsxData:         { get(){ return state.xlsxData;         }, set(v){ state.xlsxData=v;         } },
  logsData:         { get(){ return state.logsData;         }, set(v){ state.logsData=v;         } },
  slaDsHistory:      { get(){ return state.slaDsHistory;      }, set(v){ state.slaDsHistory=v;      } },
  slaDsBases:        { get(){ return state.slaDsBases;        }, set(v){ state.slaDsBases=v;        } },
  slaDsActiveBases:  { get(){ return state.slaDsActiveBases;  }, set(v){ state.slaDsActiveBases=v;  } },
  slaDsActiveBases2: { get(){ return state.slaDsActiveBases2; }, set(v){ state.slaDsActiveBases2=v; } },
  slaDsPeriod:       { get(){ return state.slaDsPeriod;       }, set(v){ state.slaDsPeriod=v;       } },
  slaDsCompare:      { get(){ return state.slaDsCompare;      }, set(v){ state.slaDsCompare=v;      } },
  cepCache:         { get(){ return state.cepCache;         }, set(v){ state.cepCache=v;         } },
  sortStates:       { get(){ return state.sortStates;       }, set(v){ state.sortStates=v;       } },
  libSel:           { get(){ return state.libSel;           }, set(v){ state.libSel=v;           } },
});
