"""empty message

Revision ID: 32ab0b9d7785
Revises: 
Create Date: 2026-06-07 00:38:04.160680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '32ab0b9d7785'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cep_cache',
    sa.Column('cep', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cidade', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bairro', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uf', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('cep')
    )
    op.create_table('operacao',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('app_user',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('empresa', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('operacao_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('base_scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extra_perms', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('denied_perms', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['operacao_id'], ['operacao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('base',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('operacao_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['operacao_id'], ['operacao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operacao_id', 'slug', name='uq_base_op_slug')
    )
    with op.batch_alter_table('base', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_base_operacao_id'), ['operacao_id'], unique=False)

    op.create_table('driver',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('normalized_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('documento', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('telefone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['base_id'], ['base.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_id', 'normalized_key', name='uq_driver_base_key')
    )
    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_driver_base_id'), ['base_id'], unique=False)

    op.create_table('liberacao',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('observacao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['base_id'], ['base.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('liberacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_liberacao_base_id'), ['base_id'], unique=False)

    op.create_table('upload',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('base_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('rows_parsed', sa.Integer(), nullable=False),
    sa.Column('rows_kept', sa.Integer(), nullable=False),
    sa.Column('rows_rejected', sa.Integer(), nullable=False),
    sa.Column('error_log', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['base_id'], ['base.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upload_base_id'), ['base_id'], unique=False)

    op.create_table('user_base',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['base_id'], ['base.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'base_id')
    )
    op.create_table('package',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('upload_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('driver_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('finalizado_at', sa.DateTime(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['base_id'], ['base.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['upload.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_id', 'codigo', name='uq_package_base_codigo')
    )
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_package_base_id'), ['base_id'], unique=False)

    op.create_table('sla_ds_record',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('upload_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('data_pt_br', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sla_pct', sa.Float(), nullable=True),
    sa.Column('sla_rec', sa.Integer(), nullable=True),
    sa.Column('sla_ent', sa.Integer(), nullable=True),
    sa.Column('ds_pct', sa.Float(), nullable=True),
    sa.Column('ds_rec', sa.Integer(), nullable=True),
    sa.Column('ds_ent', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['base_id'], ['base.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['upload.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_id', 'data_pt_br', name='uq_sla_ds_base_dia')
    )
    with op.batch_alter_table('sla_ds_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sla_ds_record_base_id'), ['base_id'], unique=False)

    op.create_table('snapshot',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('data_pt_br', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hora', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sla_pct', sa.Float(), nullable=True),
    sa.Column('ds_pct', sa.Float(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('entregues', sa.Integer(), nullable=False),
    sa.Column('em_rota', sa.Integer(), nullable=False),
    sa.Column('ocorrencias', sa.Integer(), nullable=False),
    sa.Column('faltantes', sa.Integer(), nullable=False),
    sa.Column('devolvidos', sa.Integer(), nullable=False),
    sa.Column('outros', sa.Integer(), nullable=False),
    sa.Column('upload_csv_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('upload_xlsx_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['base_id'], ['base.id'], ),
    sa.ForeignKeyConstraint(['upload_csv_id'], ['upload.id'], ),
    sa.ForeignKeyConstraint(['upload_xlsx_id'], ['upload.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_id', 'data_pt_br', name='uq_snapshot_base_dia')
    )
    with op.batch_alter_table('snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snapshot_base_id'), ['base_id'], unique=False)

    op.create_table('snapshot_driver',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('snapshot_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('driver_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('driver_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('saiu', sa.Integer(), nullable=False),
    sa.Column('entregues', sa.Integer(), nullable=False),
    sa.Column('em_rota', sa.Integer(), nullable=False),
    sa.Column('ocorrencias', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('snapshot_driver', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snapshot_driver_snapshot_id'), ['snapshot_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snapshot_driver', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snapshot_driver_snapshot_id'))

    op.drop_table('snapshot_driver')
    with op.batch_alter_table('snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snapshot_base_id'))

    op.drop_table('snapshot')
    with op.batch_alter_table('sla_ds_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sla_ds_record_base_id'))

    op.drop_table('sla_ds_record')
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_package_base_id'))

    op.drop_table('package')
    op.drop_table('user_base')
    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upload_base_id'))

    op.drop_table('upload')
    with op.batch_alter_table('liberacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_liberacao_base_id'))

    op.drop_table('liberacao')
    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_base_id'))

    op.drop_table('driver')
    with op.batch_alter_table('base', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_base_operacao_id'))

    op.drop_table('base')
    op.drop_table('app_user')
    op.drop_table('operacao')
    op.drop_table('cep_cache')
    # ### end Alembic commands ###
